/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: 36a2524249c7c4c4fab0f640c2c354fd)
interface __BaseEnv_Env {
	IMAGE_BUCKET: R2Bucket;
	IMAGE_TRANSFORMATIONS: ImagesBinding;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
